/**
 * The files that go into a package next to the generated app: how to start it (Linux/macOS
 * and Windows) and what to know about it. Plain text, no secrets.
 */

const HTTPS_PORT_MOVE = "127.0.0.1:8081";

const startSh = (name) => `#!/bin/sh
# Starts ${name}. Needs Docker with Compose v2.
#   ./start.sh                            the app at http://localhost
#   ./start.sh --domain gis.example.org   the app at https://gis.example.org (see README.md)
#   add --internal-cert for a name only your own network knows (a certificate made by Caddy)
set -e
cd "$(dirname "$0")/deploy"

while [ $# -gt 0 ]; do
  case "$1" in
    --domain) DOMAIN="$2"; shift 2 ;;
    --internal-cert) CADDY_TLS=internal; shift ;;
    -h|--help) sed -n '2,5p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [ -n "\${DOMAIN:-}" ]; then
  # Caddy takes ports 80/443 and gets the certificate; nginx stays behind it
  export DOMAIN NGINX_BIND=${HTTPS_PORT_MOVE} COMPOSE_PROFILES=https
  export CADDY_TLS="\${CADDY_TLS:-auto}"
fi

export DOCKER_BUILDKIT=1
docker compose up -d --build

if [ -n "\${DOMAIN:-}" ]; then URL="https://$DOMAIN"; else URL="http://localhost"; fi
echo
echo "Started. The first start builds the images and loads the data (several minutes)."
echo "Open $URL when 'docker compose ps' (in the deploy folder) shows the data-importer as exited."
`;

const startPs1 = (
  name
) => `# Starts ${name}. Needs Docker Desktop (or Docker with Compose v2).
#   .\\start.ps1                              the app at http://localhost
#   .\\start.ps1 -Domain gis.example.org      the app at https://gis.example.org (see README.md)
#   add -InternalCert for a name only your own network knows (a certificate made by Caddy)
param([string]$Domain = "", [switch]$InternalCert)
$ErrorActionPreference = "Stop"
Set-Location (Join-Path $PSScriptRoot "deploy")

if ($Domain) {
  # Caddy takes ports 80/443 and gets the certificate; nginx stays behind it
  $env:DOMAIN = $Domain
  $env:NGINX_BIND = "${HTTPS_PORT_MOVE}"
  $env:COMPOSE_PROFILES = "https"
  if ($InternalCert) { $env:CADDY_TLS = "internal" }
}

$env:DOCKER_BUILDKIT = "1"
docker compose up -d --build
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

$url = if ($Domain) { "https://$Domain" } else { "http://localhost" }
Write-Host ""
Write-Host "Started. The first start builds the images and loads the data (several minutes)."
Write-Host "Open $url when 'docker compose ps' (in the deploy folder) shows the data-importer as exited."
`;

const editingSection = `
## Editing

Some layers can be edited in the map. Changing data asks for an account: user \`editor\`. Its
password is not part of this package; whoever generated it has it (GISPublisher shows it when the
package is made and keeps it in \`.gp-edit-auth.json\` next to the generated app). Use HTTPS when
the app is reachable from the internet, or the password travels unencrypted.
`;

const readme = ({ name, editing }) => `# ${name}

A web map generated by GISPublisher: a Vue client, a Spring server, PostGIS, GeoServer and nginx,
started together with Docker Compose. Nothing else is needed on the machine.

## Requirements

- Docker Engine or Docker Desktop with Compose v2 (\`docker compose version\`).
- About 4 GB of free memory (8 GB is comfortable) and 10 GB of disk.
- Internet access the first time: the images are built from source and download their dependencies.

## Start

    ./start.sh              (Linux, macOS)
    .\\start.ps1             (Windows PowerShell)

The first start takes several minutes (it builds the images and loads the data). Then open
http://localhost. Port 80 must be free; nothing else of the app is reachable from the network.

To stop it: \`docker compose --profile https stop\` inside the \`deploy\` folder. To remove it and its
data: \`docker compose --profile https down -v\`. (Without \`--profile https\` the HTTPS service, when
you started it, is left running.)

## HTTPS with a domain

1. Point a domain name at this machine (an A record) and open ports 80 and 443 to the internet.
2. Start it with the domain:

       ./start.sh --domain gis.example.org
       .\\start.ps1 -Domain gis.example.org

Caddy gets a free Let's Encrypt certificate for the domain and renews it by itself. To be told
when a certificate is about to expire, add your email to \`deploy/caddy/Caddyfile.conf\` (an
example is in the file). To go back to plain HTTP, start it without the domain.

For a name that only your own network knows (no public DNS, so Let's Encrypt cannot check it), add
\`--internal-cert\` (\`-InternalCert\` on Windows): Caddy makes its own certificate, and browsers warn
until they are told to trust it.
${editing ? editingSection : ""}
## Data

- Loading: the \`data-importer\` service loads the files in \`deploy/importer/data\` each time the
  stack starts, and only the layers whose file changed.
- To load new data of the same layers and fields: replace the files there and run
  \`docker compose run --rm data-importer\` inside \`deploy\`. If layers or fields changed, start from an
  empty database instead: \`docker compose --profile https down -v\` and start again.
- Backup:

      docker compose exec -T postgres sh -c 'pg_dump -U "$POSTGRES_USER" "$POSTGRES_DB"' > backup.sql

  Restore into a running app:
  \`docker compose exec -T postgres sh -c 'psql -U "$POSTGRES_USER" "$POSTGRES_DB"' < backup.sql\`.

## Security

- The passwords of the database and of GeoServer were made for this package and are in
  \`deploy/.env\` and \`server/src/main/resources/application-prod.yml\`. Keep the package private, or
  change them there (before the first start).
- GeoServer's administration pages and its REST API are not served by nginx. The internal services
  publish no ports.

## What is in here

- \`client\`, \`server\`: the sources of the web app and its API (built by Docker).
- \`deploy\`: \`docker-compose.yml\`, nginx and Caddy settings, and the data to load.
- \`qgis\`: the QGIS processing service and the models of the app.
`;

/**
 * @param {{name: string, editing: boolean}} app
 * @returns {Record<string, string>} relative path (inside the package folder) -> content
 */
export function packageFiles({ name, editing = false }) {
  return {
    "README.md": readme({ name, editing }),
    "start.sh": startSh(name),
    "start.ps1": startPs1(name),
  };
}
